name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
          registry: ghcr.io
          repository: parviste/metaflow_metadata_service
          tag_with_ref: true
